### ISSUE TITLE
Autostart adapter

### ISSUE THREAD

**Issue by effgarces** [Vulisha/Dwarf2Lx200Adapter#1]
I just installed the adapter on my dwarf II and seems be working perfectly, I was just wondering if there's any way to make it autostart when the Dwarf II boots?

**Comment by Vulisha** [comment]
I was looking at that as well, unfortunately there does not seem to be any of popular autostart options
Does not have Cron, does not have systemctl it has init.d but no update -rc.d...
Something does exist as it autostarts dwarf apps, but did not manage to investigate. I do plan to do it in future, if Dwarflab does not make it by them self.

**Comment by vprenner** [comment]
It's not hard to do :)
create a file called /etc/init.d/S99_lx200
put this as contents:
#!/bin/bash
/usr/bin/Dwarf2Lx200Adapter &

be sure to add the '&' at the end of the line. i am not sure it's needed, but it could stop the startup process if you don't add it (i wasn't brave enough to try).

**Comment by Vulisha** [comment]
Checked this works! Only one single thing needed, you need to 
chmod +x  /etc/init.d/S99_lx200
